### ISSUE TITLE
Location of the Dataset

### ISSUE THREAD

**Issue by mmaaz60** [huyvvo/rOSD#1]
Hi,

By following the instructions in the README.md, I am getting the attached error.
![image](https://user-images.githubusercontent.com/55104795/126816264-146edc20-9ad0-4c67-af46-6e042abe3539.png)

It looks like I have to download the dataset and put it somewhere. Can you please guide me? Thanks

**Comment by mmaaz60** [comment]
What I actually want is a script that takes an image file path (`.jpg`) as input and outputs the regions as explained in the section 3.1 of the paper. I am not very much familiar with Matlab so any help in this regard will be appreciated. Looking forward to hearing from you. @huyvvo

**Comment by huyvvo** [comment]
Hi @mmaaz60, 
To run the demo code on the VOC_6x2 dataset, please download it [here](https://drive.google.com/drive/folders/191WgX9fkrXr-AUVdIh57QWaEEXuaZzre?usp=sharing) and put it in `rOSD/data`.

I don't have a script to extract proposals for a single image but you can walk around with the current code. The steps to follow are:
  - Create folder `<your_dataset>/mixed` in `rOSD/data` (rOSD is the git repo that contains 'rOSD' and 'OSD'), 'your_dataset' is your dataset name.
  - Create `mixed.mat` in `<your_dataset>/mixed` that is a matlab struct with fields 'images' and 'bboxes'. 'Images' is a cell containing RGB images and 'bboxes' is a cell containing ground-truth bounding boxes. 'bboxes' is unnecessary in proposal generation so you can assign it to `{[]}`. An example code to create this .mat file from the image path is
  ```
imdb = struct; 
imdb.images = {}; 
imdb.bboxes = {}; 
imdb.images{1,1} = imread(<image_path>); 
imdb.bboxes{1,1} = [];
save('rOSD/data/<your_dataset>/mixed/mixed.mat', '-struct', 'imdb');
```
See `rOSD/data/vocx/mixed/mixed.mat` that you download from the link above for an example.
  - Modify function get_classes in `rOSD/commons/utils/get_classes.m` such that `get_classes(<your_dataset>)` returns `{'mixed'}`. For example, add 
  ```
elseif strcmp(imgset, '<your_dataset>') 
  classes = {'mixed'};
```
  to its if..else part.
  - Run `set_path` then the first 45 lines of `rOSD/run_proposals` with the first two lines modified to 
 ```
original_imgset = '<your_dataset>';
cnn_imgset = '<your_dataset>_cnn';
```
You should get the proposals in `rOSD/data/<your_dataset>_cnn/mixed/mixed_lite.mat`

I unfortunately have not had time to check these steps. Please let me know if you are able to extract proposals with this.

**Comment by mmaaz60** [comment]
> Hi @mmaaz60,
> To run the demo code on the VOC_6x2 dataset, please download it [here](https://drive.google.com/drive/folders/191WgX9fkrXr-AUVdIh57QWaEEXuaZzre?usp=sharing) and put it in `rOSD/data`.
> 
> I don't have a script to extract proposals for a single image but you can walk around with the current code. The steps to follow are:
> 
> * Create folder `<your_dataset>/mixed` in `rOSD/data` (rOSD is the git repo that contains 'rOSD' and 'OSD'), 'your_dataset' is your dataset name.
> * Create `mixed.mat` in `<your_dataset>/mixed` that is a matlab struct with fields 'images' and 'bboxes'. 'Images' is a cell containing RGB images and 'bboxes' is a cell containing ground-truth bounding boxes. 'bboxes' is unnecessary in proposal generation so you can assign it to `{[]}`. An example code to create this .mat file from the image path is
> 
> ```
> imdb = struct; 
> imdb.images = {}; 
> imdb.bboxes = {}; 
> imdb.images{1,1} = imread(<image_path>); 
> imdb.bboxes{1,1} = [];
> save('rOSD/data/<your_dataset>/mixed/mixed.mat', '-struct', 'imdb');
> ```
> 
> See `rOSD/data/vocx/mixed/mixed.mat` that you download from the link above for an example.
> 
> * Modify function get_classes in `rOSD/commons/utils/get_classes.m` such that `get_classes(<your_dataset>)` returns `{'mixed'}`. For example, add
> 
> ```
> elseif strcmp(imgset, '<your_dataset>') 
> classes = {'mixed'};
> ```
> 
> to its if..else part.
> 
> * Run `set_path` then the first 45 lines of `rOSD/run_proposals` with the first two lines modified to
> 
> ```
> original_imgset = '<your_dataset>';
> cnn_imgset = '<your_dataset>_cnn';
> ```
> 
> You should get the proposals in `rOSD/data/<your_dataset>_cnn/mixed/mixed_lite.mat`
> 
> I unfortunately have not had time to check these steps. Please let me know if you are able to extract proposals with this.

Thank you for your detailed response. It was really helpful.
